// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhom7_webTourdulich.Models;

#nullable disable

namespace Nhom7_webTourdulich.Migrations
{
    [DbContext(typeof(QuanLyTourContext))]
    partial class QuanLyTourContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhom7_webTourdulich.Models.ChiTietHoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Hoa_Don");

<<<<<<< HEAD
                    b.Property<int>("MaKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int")
=======
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
                        .HasColumnName("Ma_Khach_Hang");

                    b.Property<decimal>("GiaTour")
                        .HasColumnType("money")
                        .HasColumnName("Gia_Tour");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("So_Luong");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("money")
                        .HasColumnName("Thanh_Tien")
                        .HasComputedColumnSql("([Gia_Tour]*[So_Luong])", true);

                    b.HasKey("MaHoaDon", "MaKhachHang")
<<<<<<< HEAD
                        .HasName("PK__ChiTietH__A294B5FBC6D9C49E");
=======
                        .HasName("PK__ChiTietH__A294B5FB13EB6400");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasIndex("MaKhachHang");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Chuc_Vu");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ten_Chuc_Vu");

                    b.HasKey("MaChucVu")
<<<<<<< HEAD
                        .HasName("PK__ChucVu__EFE449720DAF3C2C");
=======
                        .HasName("PK__ChucVu__EFE449723DD79615");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.DiemDen", b =>
                {
                    b.Property<string>("MaDiemDen")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Diem_Den");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Thanh_Pho");

                    b.HasKey("MaDiemDen")
<<<<<<< HEAD
                        .HasName("PK__DiemDen__34267B5EDBE1CB85");
=======
                        .HasName("PK__DiemDen__34267B5E86B79B2E");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.ToTable("DiemDen", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.GiaTour", b =>
                {
                    b.Property<string>("MaGiaTour")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Gia_Tour");

                    b.Property<decimal>("Gia")
                        .HasColumnType("money");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Bat_Dau");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Ket_Thuc");

                    b.HasKey("MaGiaTour")
<<<<<<< HEAD
                        .HasName("PK__GiaTour__6B20AB462CA1B26C");
=======
                        .HasName("PK__GiaTour__6B20AB467AE194FF");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.ToTable("GiaTour", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Hoa_Don");

                    b.Property<string>("DiemDon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Diem_Don");

                    b.Property<TimeOnly>("GioDi")
                        .HasColumnType("time")
                        .HasColumnName("Gio_Di");

<<<<<<< HEAD
                    b.Property<int>("MaKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int")
=======
                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
                        .HasColumnName("Ma_Khach_Hang");

                    b.Property<string>("MaNhomTour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Nhom_Tour");

                    b.Property<DateOnly>("NgayDi")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Di");

                    b.Property<DateOnly>("NgayLap")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Lap");

                    b.Property<string>("ThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Thanh_Toan");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("money")
                        .HasColumnName("Tong_Tien");

                    b.HasKey("MaHoaDon")
<<<<<<< HEAD
                        .HasName("PK__HoaDon__91EF063FC4157924");
=======
                        .HasName("PK__HoaDon__91EF063FFF61E16D");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhomTour");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.KhachHang", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Ma_Khach_Hang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

=======
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Khach_Hang");

>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Dia_Chi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Gioi_Tinh");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Hinh_Anh");

<<<<<<< HEAD
                    b.Property<string>("MaTour")
                        .HasColumnType("varchar(20)");

=======
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Quoc_Tich");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaKhachHang")
<<<<<<< HEAD
                        .HasName("PK__KhachHan__37BB3C42DB802C2D");

                    b.HasIndex("MaTour");
=======
                        .HasName("PK__KhachHan__37BB3C420E78E4C3");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.KhuyenMai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Khuyen_Mai");

                    b.Property<string>("GiaGiam")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Gia_Giam");

                    b.Property<string>("MaGiaTour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Gia_Tour");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Bat_Dau");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Ket_Thuc");

                    b.Property<double?>("PhanTramGiam")
                        .HasColumnType("float")
                        .HasColumnName("Phan_Tram_Giam");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ten_Khuyen_Mai");

                    b.HasKey("MaKhuyenMai")
<<<<<<< HEAD
                        .HasName("PK__KhuyenMa__19F298C55EA7F7FF");
=======
                        .HasName("PK__KhuyenMa__19F298C5BD513EEA");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasIndex("MaGiaTour");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.LoaiTour", b =>
                {
                    b.Property<string>("MaLoaiTour")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Loai_Tour");

                    b.Property<string>("TenLoaiTour")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ten_Loai_Tour");

                    b.HasKey("MaLoaiTour")
<<<<<<< HEAD
                        .HasName("PK__LoaiTour__ACE9E7DA26904217");
=======
                        .HasName("PK__LoaiTour__ACE9E7DAC83A2409");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.ToTable("LoaiTour", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.NhanVien", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Ma_Nhan_Vien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

=======
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Nhan_Vien");

>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Hinh_Anh");

<<<<<<< HEAD
                    b.Property<string>("LinkFB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkIG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkZL")
                        .HasColumnType("nvarchar(max)");

=======
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Chuc_Vu");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNhanVien")
<<<<<<< HEAD
                        .HasName("PK__NhanVien__7AB89689143E91C2");
=======
                        .HasName("PK__NhanVien__7AB896891713CABD");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.NhomTour", b =>
                {
                    b.Property<string>("MaNhomTour")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Nhom_Tour");

                    b.Property<string>("DiemXuatPhat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Diem_Xuat_Phat");

                    b.Property<string>("MaTour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Tour");

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Trang_Thai");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Ket_Thuc");

                    b.Property<DateOnly>("NgayKhoiHanh")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_Khoi_Hanh");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Noi_Dung");

                    b.Property<string>("SoLuongNguoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("So_Luong_Nguoi");

                    b.HasKey("MaNhomTour")
<<<<<<< HEAD
                        .HasName("PK__NhomTour__3D75DE0FE9D64DA2");
=======
                        .HasName("PK__NhomTour__3D75DE0FA98AB25B");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasIndex("MaTour");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("NhomTour", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.PhuongTien", b =>
                {
                    b.Property<string>("MaPhuongTien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Phuong_Tien");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Trang_Thai");

                    b.HasKey("MaPhuongTien")
<<<<<<< HEAD
                        .HasName("PK__PhuongTi__09E91370F7B68465");
=======
                        .HasName("PK__PhuongTi__09E91370EB43D8E5");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.ToTable("PhuongTien", (string)null);
                });

<<<<<<< HEAD
=======
            modelBuilder.Entity("Nhom7_webTourdulich.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTermsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepeatPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registers");
                });

>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
            modelBuilder.Entity("Nhom7_webTourdulich.Models.Tour", b =>
                {
                    b.Property<string>("MaTour")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Tour");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Hinh_Anh");

                    b.Property<string>("MaDiemDen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Diem_Den");

                    b.Property<string>("MaGiaTour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Gia_Tour");

                    b.Property<string>("MaLoaiTour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Loai_Tour");

                    b.Property<string>("SoLuongNguoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("So_Luong_Nguoi");

<<<<<<< HEAD
                    b.Property<string>("SoNgay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
=======
                    b.Property<int>("SoNgay")
                        .HasColumnType("int")
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
                        .HasColumnName("So_Ngay");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTour")
<<<<<<< HEAD
                        .HasName("PK__Tour__1C19FFEA992E3B6A");
=======
                        .HasName("PK__Tour__1C19FFEADA1259D4");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasIndex("MaDiemDen");

                    b.HasIndex("MaGiaTour");

                    b.HasIndex("MaLoaiTour");

                    b.ToTable("Tour", (string)null);
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.TrangThai", b =>
                {
                    b.Property<string>("MaTrangThai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ma_Trang_Thai");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ten_Trang_Thai");

                    b.HasKey("MaTrangThai")
<<<<<<< HEAD
                        .HasName("PK__TrangTha__B9CD9D6BA20F14FE");
=======
                        .HasName("PK__TrangTha__B9CD9D6BDB4AF9BE");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.ToTable("TrangThai", (string)null);
                });

<<<<<<< HEAD
=======
            modelBuilder.Entity("Nhom7_webTourdulich.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Remember")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
            modelBuilder.Entity("Nhom7_webTourdulich.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Nhom7_webTourdulich.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__ChiTietHo__Ma_Ho__151B244E");
=======
                        .HasConstraintName("FK__ChiTietHo__Ma_Ho__5629CD9C");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasOne("Nhom7_webTourdulich.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__ChiTietHo__Ma_Kh__160F4887");
=======
                        .HasConstraintName("FK__ChiTietHo__Ma_Kh__571DF1D5");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.HoaDon", b =>
                {
                    b.HasOne("Nhom7_webTourdulich.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__HoaDon__Ma_Khach__10566F31");
=======
                        .HasConstraintName("FK__HoaDon__Ma_Khach__5165187F");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasOne("Nhom7_webTourdulich.Models.NhomTour", "MaNhomTourNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhomTour")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__HoaDon__Ma_Nhom___114A936A");
=======
                        .HasConstraintName("FK__HoaDon__Ma_Nhom___52593CB8");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNhomTourNavigation");
                });

<<<<<<< HEAD
            modelBuilder.Entity("Nhom7_webTourdulich.Models.KhachHang", b =>
                {
                    b.HasOne("Nhom7_webTourdulich.Models.Tour", "Tour")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaTour");

                    b.Navigation("Tour");
                });

=======
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
            modelBuilder.Entity("Nhom7_webTourdulich.Models.KhuyenMai", b =>
                {
                    b.HasOne("Nhom7_webTourdulich.Models.GiaTour", "MaGiaTourNavigation")
                        .WithMany("KhuyenMais")
                        .HasForeignKey("MaGiaTour")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__KhuyenMai__Ma_Gi__6C190EBB");
=======
                        .HasConstraintName("FK__KhuyenMai__Ma_Gi__59FA5E80");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.Navigation("MaGiaTourNavigation");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.NhanVien", b =>
                {
                    b.HasOne("Nhom7_webTourdulich.Models.ChucVu", "MaChucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__NhanVien__Ma_Chu__5812160E");
=======
                        .HasConstraintName("FK__NhanVien__Ma_Chu__4316F928");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.Navigation("MaChucVuNavigation");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.NhomTour", b =>
                {
                    b.HasOne("Nhom7_webTourdulich.Models.Tour", "MaTourNavigation")
                        .WithMany("NhomTours")
                        .HasForeignKey("MaTour")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__NhomTour__Ma_Tou__0B91BA14");
=======
                        .HasConstraintName("FK__NhomTour__Ma_Tou__4CA06362");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasOne("Nhom7_webTourdulich.Models.TrangThai", "MaTrangThaiNavigation")
                        .WithMany("NhomTours")
                        .HasForeignKey("MaTrangThai")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__NhomTour__Ma_Tra__0C85DE4D");
=======
                        .HasConstraintName("FK__NhomTour__Ma_Tra__4D94879B");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.Navigation("MaTourNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.Tour", b =>
                {
                    b.HasOne("Nhom7_webTourdulich.Models.DiemDen", "MaDiemDenNavigation")
                        .WithMany("Tours")
                        .HasForeignKey("MaDiemDen")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__Tour__Ma_Diem_De__76969D2E");
=======
                        .HasConstraintName("FK__Tour__Ma_Diem_De__49C3F6B7");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasOne("Nhom7_webTourdulich.Models.GiaTour", "MaGiaTourNavigation")
                        .WithMany("Tours")
                        .HasForeignKey("MaGiaTour")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__Tour__Ma_Gia_Tou__75A278F5");
=======
                        .HasConstraintName("FK__Tour__Ma_Gia_Tou__48CFD27E");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.HasOne("Nhom7_webTourdulich.Models.LoaiTour", "MaLoaiTourNavigation")
                        .WithMany("Tours")
                        .HasForeignKey("MaLoaiTour")
                        .IsRequired()
<<<<<<< HEAD
                        .HasConstraintName("FK__Tour__Ma_Loai_To__74AE54BC");
=======
                        .HasConstraintName("FK__Tour__Ma_Loai_To__47DBAE45");
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5

                    b.Navigation("MaDiemDenNavigation");

                    b.Navigation("MaGiaTourNavigation");

                    b.Navigation("MaLoaiTourNavigation");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.DiemDen", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.GiaTour", b =>
                {
                    b.Navigation("KhuyenMais");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.KhachHang", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.LoaiTour", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.NhomTour", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.Tour", b =>
                {
<<<<<<< HEAD
                    b.Navigation("KhachHangs");

=======
>>>>>>> b5310ada0464d2eebf8d9a629d950c4f1ee8efa5
                    b.Navigation("NhomTours");
                });

            modelBuilder.Entity("Nhom7_webTourdulich.Models.TrangThai", b =>
                {
                    b.Navigation("NhomTours");
                });
#pragma warning restore 612, 618
        }
    }
}
